---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-mutual-test
spec:
  schedule: 30 * * * *
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: app
            image: alpine:latest
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              allowPrivilegeEscalation: false
            resources:
              limits:
                cpu: 50m
                memory: 32Mi
              requests:
                cpu: 0m
                memory: 16Mi
            command:
            - /bin/true
